//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [System.SerializableAttribute()]
    public class EasybotsApplicationLicence_00000000000000000000000000000001 : Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        136,
                        38,
                        133,
                        54,
                        199,
                        162,
                        180,
                        120,
                        63,
                        112,
                        214,
                        248,
                        234,
                        165,
                        68,
                        99,
                        114,
                        6,
                        226,
                        186,
                        175,
                        184,
                        26,
                        63,
                        230,
                        6,
                        183,
                        214,
                        138,
                        148,
                        252,
                        25,
                        216,
                        146,
                        99,
                        30,
                        7,
                        124,
                        100,
                        45};
            }
        }
    }
}