//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        53,
                        31,
                        145,
                        137,
                        17,
                        22,
                        202,
                        147,
                        128,
                        74,
                        210,
                        13,
                        254,
                        239,
                        156,
                        243,
                        28,
                        122,
                        244,
                        148,
                        64,
                        53,
                        93,
                        6,
                        15,
                        202,
                        53,
                        106,
                        62,
                        171,
                        148,
                        211,
                        214,
                        94,
                        41,
                        175,
                        188,
                        233,
                        165,
                        221};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("5df7b144-8224-43ab-b3fa-47431f0f1f46");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        90,
                        186,
                        211,
                        162,
                        112,
                        6,
                        121,
                        154,
                        156,
                        158,
                        44,
                        245,
                        161,
                        212,
                        238,
                        214,
                        171,
                        53,
                        128,
                        19,
                        133,
                        12,
                        104,
                        39,
                        160,
                        66,
                        158,
                        104,
                        63,
                        20,
                        219,
                        26,
                        65,
                        57,
                        85,
                        234,
                        228,
                        29,
                        203,
                        134};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("5b5bfd20-dc52-4453-acd9-0eea73095829");
            }
        }
    }
}