//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        3,
                        135,
                        95,
                        25,
                        80,
                        5,
                        50,
                        216,
                        205,
                        244,
                        20,
                        94,
                        106,
                        113,
                        175,
                        212,
                        6,
                        66,
                        120,
                        58,
                        27,
                        164,
                        111,
                        235,
                        174,
                        45,
                        17,
                        126,
                        88,
                        216,
                        153,
                        211,
                        214,
                        249,
                        168,
                        99,
                        5,
                        44,
                        77,
                        236};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("177294bb-608a-47c3-bb93-13139d9f3ca4");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        34,
                        252,
                        142,
                        6,
                        76,
                        60,
                        203,
                        187,
                        155,
                        1,
                        30,
                        252,
                        61,
                        86,
                        220,
                        158,
                        11,
                        87,
                        80,
                        115,
                        37,
                        210,
                        170,
                        27,
                        28,
                        245,
                        165,
                        68,
                        191,
                        210,
                        156,
                        159,
                        110,
                        33,
                        212,
                        205,
                        226,
                        77,
                        62,
                        188};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("5b5bfd20-dc52-4453-acd9-0eea73095829");
            }
        }
    }
}