//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        75,
                        67,
                        133,
                        66,
                        124,
                        154,
                        190,
                        128,
                        136,
                        56,
                        191,
                        52,
                        19,
                        18,
                        245,
                        174,
                        164,
                        123,
                        137,
                        31,
                        50,
                        222,
                        170,
                        44,
                        167,
                        120,
                        169,
                        219,
                        68,
                        50,
                        12,
                        191,
                        29,
                        132,
                        56,
                        103,
                        98,
                        29,
                        33,
                        217};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("9a258f2e-b03c-4b55-afe3-8b13bbc27c6d");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        129,
                        223,
                        85,
                        25,
                        50,
                        158,
                        226,
                        96,
                        10,
                        205,
                        132,
                        163,
                        234,
                        129,
                        113,
                        240,
                        127,
                        57,
                        2,
                        109,
                        44,
                        43,
                        99,
                        14,
                        244,
                        103,
                        71,
                        87,
                        129,
                        128,
                        178,
                        111,
                        139,
                        108,
                        157,
                        66,
                        158,
                        250,
                        213,
                        181};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("5b5bfd20-dc52-4453-acd9-0eea73095829");
            }
        }
    }
}