//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [System.SerializableAttribute()]
    public class EasybotsApplicationLicence_8b8cf90c24fb479f923155ac048ffa75 : Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        14,
                        176,
                        238,
                        0,
                        100,
                        177,
                        137,
                        142,
                        125,
                        108,
                        108,
                        158,
                        56,
                        197,
                        12,
                        23,
                        253,
                        80,
                        39,
                        48,
                        150,
                        9,
                        9,
                        253,
                        103,
                        169,
                        174,
                        67,
                        40,
                        108,
                        153,
                        216,
                        183,
                        44,
                        33,
                        101,
                        230,
                        99,
                        156,
                        128};
            }
        }
    }
}