//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        4,
                        33,
                        140,
                        225,
                        174,
                        97,
                        76,
                        91,
                        87,
                        249,
                        170,
                        115,
                        187,
                        38,
                        141,
                        68,
                        177,
                        158,
                        198,
                        5,
                        127,
                        46,
                        113,
                        98,
                        91,
                        144,
                        208,
                        4,
                        195,
                        241,
                        74,
                        55,
                        138,
                        213,
                        79,
                        167,
                        248,
                        224,
                        134,
                        9};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("baf32582-e271-43fc-a25c-e45bfddde2e2");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        56,
                        26,
                        170,
                        124,
                        29,
                        94,
                        185,
                        70,
                        102,
                        168,
                        209,
                        87,
                        180,
                        137,
                        150,
                        133,
                        20,
                        132,
                        250,
                        183,
                        36,
                        82,
                        141,
                        201,
                        52,
                        247,
                        129,
                        144,
                        50,
                        59,
                        141,
                        142,
                        126,
                        11,
                        52,
                        23,
                        48,
                        60,
                        52,
                        127};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("ee135651-c376-4ceb-a565-5cb8663b12e4");
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [System.SerializableAttribute()]
    public class EasybotsApplicationLicence_00000000000000000000000000000001 : Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        58,
                        49,
                        74,
                        193,
                        101,
                        31,
                        252,
                        199,
                        72,
                        221,
                        196,
                        8,
                        60,
                        144,
                        234,
                        28,
                        23,
                        20,
                        170,
                        26,
                        114,
                        122,
                        90,
                        40,
                        22,
                        181,
                        9,
                        239,
                        103,
                        145,
                        190,
                        254,
                        1,
                        13,
                        112,
                        141,
                        96,
                        66,
                        219,
                        61};
            }
        }
    }
}